FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# EasyOrder

REST APIs for Project [EasyOrder](https://github.com/DeliciousFoodEasyOrder).

## OAuth Collection [/oauth]

### Password Grant [POST /oauth/token{?grant_type,username,password}]

+ Parameters

    + grant_type : `password` (string, required) - Fixed, must be "password"

    + username : `example@email.com` (string, required) - Email or Phone

    + password : `password` (string, required) - Password
    
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"认证成功",
            "data":{
                "access_token":"xxxx.yyyy.zzzz",
                "token_type":"JWT",
                "expires_in":259200
            }
        }

## Merchant Collection [/merchants]

### Get a merchant [GET /merchants{?email,phone}]

+ Parameters

    + email : `example@email.com` (string) - Email

    + phone : `12345678901` (string) - Phone
    
+ Request

    + Headers

            Authorization: Bearer xxxx.yyyy.zzzz
            
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取商户信息成功",
            "data":{
                "merchant_id":1,
                "email":"example@email.com",
                "phone":"12345678901",
                "password":"password"
            }
        }

### Create a merchant [POST /merchants]

+ Request (application/json)

        {
            "merchant_id":null,
            "email":"example@email.com",
            "phone":"12345678901",
            "password":"password",
        }

+ Response 201 (application/json)

        {
            "code":201,
            "msg":"商户注册成功",
            "data":{
                "merchant_id":1,
                "email":"example@email.com",
                "phone":"12345678901",
                "password":"password"
            }
        }

## Order Collection [/orders]

### List orders [GET /orders{?merchant_id,status}]

+ Parameters

    + merchant_id : 1 (int, required) - Merchant ID

    + status : 1 (int) - 已完成:0, 正在做:1

+ Request

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz

+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取订单列表成功",
            "data":[{
                "order_id":1,
                "status":1,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00",
                "foods":[{
                    "food_id":1,
                    "name":"鱼香肉丝",
                    "description":"香喷喷的鱼香肉丝",
                    "price":"9.99",
                    "merchant_id":1,
                    "amount":2,
                },{
                    "food_id":2,
                    "name":"兰州拉面",
                    "description":"清真的拉面",
                    "price":"39.99",
                    "merchant_id":1,
                    "amount":1,
                }]
            },{
                "order_id":2,
                "status":0,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00",
                "foods":[{
                    "food_id":1,
                    "name":"鱼香肉丝",
                    "description":"香喷喷的鱼香肉丝",
                    "price":"9.99",
                    "merchant_id":1,
                    "amount":2,
                }]
            }]
        }
        
### Get an order [GET /orders/{id}]

+ Parameters

    + id : 1 (int, required) - Order ID

+ Request

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取订单成功",
            "data":{
                "order_id":1,
                "status":0,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00",
                "foods":[{
                    "food_id":1,
                    "name":"鱼香肉丝",
                    "description":"香喷喷的鱼香肉丝",
                    "price":"9.99",
                    "merchant_id":1,
                    "amount":2
                },{
                    "food_id":2,
                    "name":"兰州拉面",
                    "description":"清真的拉面",
                    "price":"39.99",
                    "merchant_id":1,
                    "amount":2
                }]
            }
        }
        
### Create an order [POST /orders]

+ Request (application/json)

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
    + Body
            
            {
                "order_id":null,
                "status":0,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00",
                "foods":[{
                    "food_id":1,
                    "name":"鱼香肉丝",
                    "description":"香喷喷的鱼香肉丝",
                    "price":"9.99",
                    "merchant_id":1,
                    "amount":2
                },{
                    "food_id":2,
                    "name":"兰州拉面",
                    "description":"清真的拉面",
                    "price":"39.99",
                    "merchant_id":1,
                    "amount":1
                }]
            }
            
+ Response 201 (application/json)

        {
            "code":201,
            "msg":"创建订单成功",
            "data":{
                "order_id":1,
                "status":0,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00",
                "foods":[{
                    "food_id":1,
                    "name":"鱼香肉丝",
                    "description":"香喷喷的鱼香肉丝",
                    "price":"9.99",
                    "merchant_id":1,
                    "amount":2
                },{
                    "food_id":2,
                    "name":"兰州拉面",
                    "description":"清真的拉面",
                    "price":"39.99",
                    "merchant_id":1,
                    "amount":1
                }]
            }
        }
        
### Update an order partially [PATCH /orders/{id}]

+ Parameters

    + id : 1 (int, required) - Order ID

+ Request (application/json)

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
    + Body
    
            {
                "status":0
            }

+ Response 201 (application/json)

        {
            "code":201,
            "msg":"修改订单成功",
            "data":{
                "order_id":1,
                "status":0,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00",
                "foods":[{
                    "food_id":1,
                    "name":"鱼香肉丝",
                    "description":"香喷喷的鱼香肉丝",
                    "price":"9.99",
                    "merchant_id":1,
                    "amount":2
                },{
                    "food_id":2,
                    "name":"兰州拉面",
                    "description":"清真的拉面",
                    "price":"39.99",
                    "merchant_id":1,
                    "amount":1
                }]
            }
        }
        
## Seat Collection [/seats]

### List seats [GET /seats{?merchant_id}]

+ Parameters

    + merchant_id : 1 (int, required) - Merchant ID
    
+ Request

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取商家座位信息成功",
            "data":[{
                "seat_id":1,
                "number":"1A",
                "qr_code_url":"https://www.example.com",
                "merchant_id":1
            },{
                "seat_id":2,
                "number":"1B",
                "qr_code_url":"https://www.example.com",
                "merchant_id":1
            }]
        }
        
### Create a seat [POST /seats{?merchant_id}]

+ Parameters

    + merchant_id : 1 (int, required) - Merchant ID
    
+ Request (application/json)

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
    + Body
    
            {
                "seat_id":null,
                "number":"2A",
                "qr_code_url":"https://www.example.com",
                "merchant_id":1
            }
            
+ Response 201 (application/json)

        {
            "code":201,
            "msg":"新建座位成功",
            "data":{
                "seat_id":2,
                "number":"2A",
                "qr_code_url":"https://www.example.com",
                "merchant_id":1
            }
        }

### Delete a seat [DELETE /seats/{seat_id}]

+ Parameters

    + seat_id : 1 (int, required) - Seat ID
    
+ Request

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
+ Response 204

## Food Collection [/foods]

### List foods [GET /foods{?merchant_id}]

+ Parameters

    + merchant_id : 1 (int, required) - Merchant ID
    
+ Request

    + Headers
        
            Authorization: Bearer xxxx.yyyy.zzzz
            
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取菜单成功",
            "data":[{
                "food_id":1,
                "name":"鱼香肉丝",
                "description":"香喷喷的鱼香肉丝",
                "price":"9.99",
                "merchant_id":1
            },{
                "food_id":2,
                "name":"兰州拉面",
                "description":"清真的拉面",
                "price":"39.99",
                "merchant_id":1
            }]
        }

### Get a food [GET /foods/{food_id}]

+ Parameters

    + food_id : 1 (int, required) - Food ID
    
+ Request

    + Headers
    
            Authorization: Bearer xxxx.yyyy.zzzz
            
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取菜品成功",
            "data":{
                "food_id":1,
                "name":"鱼香肉丝",
                "description":"香喷喷的鱼香肉丝",
                "price":"9.99",
                "merchant_id":1
            }
        }

### Create a food [POST /foods]

+ Request (application/json)

    + Headers

            Authorization: Bearer xxxx.yyyy.zzzz

    + Body
    
            {
                "food_id":null,
                "name":"香菇牛肉",
                "description":"好食又好看",
                "price":"13.00",
                "merchant_id":1
            }
            
+ Response 201 (application/json)

        {
            "code":201,
            "msg":"创建菜品成功",
            "data":{
                "food_id":2,
                "name":"香菇牛肉",
                "description":"好食又好看",
                "price":"13.00",
                "merchant_id":1
            }
        }
        
### Delete a food [DELETE /foods/{food_id}]

+ Parameters

    + food_id : 1 (int, required) - Food ID

+ Request (application/json)

    + Headers
    
            Authorization: Bearer xxxx.yyyy.zzzz

+ Response 204