FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# EasyOrder

REST APIs for Project [EasyOrder](https://github.com/DeliciousFoodEasyOrder).

## JWT Collection [/auth]

### Get a JWT [GET /auth{?email,phone,password}]



    - email : `example@email.com` (string) - Email
    - phone : `12345678901` (string) - Phone
    - password : `password` (string, required) - Password
    
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"认证成功",
            "data":{
                "jwt":"xxxx.yyyy.zzzz"
            }
        }

## Merchants Collection [/merchants]

### Create a merchant [POST /merchants]

+ Request (application/json)

        {
            "merchant_id":null,
            "email":"example@email.com",
            "phone":"12345678901",
            "password":"password",
        }

+ Response 201 (application/json)

        {
            "code":201,
            "msg":"商户注册成功"
            "data":{
                "merchant_id":1,
                "email":"example@email.com",
                "phone":"12345678901",
                "password":"password"
            }
        }