FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# EasyOrder

REST APIs for Project [EasyOrder](https://github.com/DeliciousFoodEasyOrder).

## JWT Collection [/auth]

### Get a JWT [GET /auth{?email,phone,password}]

+ Parameters

    - email : `example@email.com` (string) - Email
    - phone : `12345678901` (string) - Phone
    - password : `password` (string, required) - Password
    
+ Response 200 (application/json)

        {
            "code":200,
            "msg":"认证成功",
            "data":{
                "jwt":"xxxx.yyyy.zzzz"
            }
        }

## Merchants Collection [/merchants]

### Create a merchant [POST /merchants]

+ Request (application/json)

        {
            "merchant_id":null,
            "email":"example@email.com",
            "phone":"12345678901",
            "password":"password",
        }

+ Response 201 (application/json)

        {
            "code":201,
            "msg":"商户注册成功"
            "data":{
                "merchant_id":1,
                "email":"example@email.com",
                "phone":"12345678901",
                "password":"password"
            }
        }
        
## Orders Collection [/orders]

### List orders [GET /orders{?merchant_id,status}]

+ Parameters

    - merchant_id : 1 (int) - Merchant ID
    - status : 1 (int) - 已完成:0, 正在做:1

+ Request

    + Headers
        
            Authorization:JWT xxxx.yyyy.zzzz

+ Response 200 (application/json)

        {
            "code":200,
            "msg":"获取订单列表成功",
            "data":[{
                "order_id":1,
                "status":1,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00"
            },{
                "order_id":2,
                "status":0,
                "seat_id":1,
                "customer_id":1,
                "merchant_id":1,
                "order_time":"2018-01-01 12:00:00",
                "complete_time":"2018-01-02 12:00:00"
            }]
        }